package com.pavikumbhar.springboot.model;
// Generated 21 Oct, 2016 3:00:38 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * QrtzCronTriggers generated by hbm2java
 */
@Entity
@Table(name="QRTZ_CRON_TRIGGERS")
public class QrtzCronTriggers  implements java.io.Serializable {


    //private QrtzCronTriggersId id;
     private QrtzTriggersId id;
     private QrtzTriggers qrtzTriggers;
     private String cronExpression;
     private String timeZoneId;

    public QrtzCronTriggers() {
    }

	
    public QrtzCronTriggers(QrtzTriggers qrtzTriggers, String cronExpression) {
        this.qrtzTriggers = qrtzTriggers;
        this.cronExpression = cronExpression;
    }
    public QrtzCronTriggers(QrtzTriggers qrtzTriggers, String cronExpression, String timeZoneId) {
       this.qrtzTriggers = qrtzTriggers;
       this.cronExpression = cronExpression;
       this.timeZoneId = timeZoneId;
    }
    
   /*
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="triggerName", column=@Column(name="TRIGGER_NAME", nullable=false, length=200) ), 
        @AttributeOverride(name="triggerGroup", column=@Column(name="TRIGGER_GROUP", nullable=false, length=200) ) } )
    public QrtzCronTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzCronTriggersId id) {
        this.id = id;
    }
*/
    
        @EmbeddedId
        @AttributeOverrides( {
        @AttributeOverride(name="schedName", column=@Column(name="SCHED_NAME", nullable=false, length=120) ), 
        @AttributeOverride(name="triggerName", column=@Column(name="TRIGGER_NAME", nullable=false, length=200) ), 
        @AttributeOverride(name="triggerGroup", column=@Column(name="TRIGGER_GROUP", nullable=false, length=200) ) } )
    public QrtzTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzTriggersId id) {
        this.id = id;
    }
    
@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public QrtzTriggers getQrtzTriggers() {
        return this.qrtzTriggers;
    }
    
    public void setQrtzTriggers(QrtzTriggers qrtzTriggers) {
        this.qrtzTriggers = qrtzTriggers;
    }

    
    @Column(name="CRON_EXPRESSION", nullable=false, length=120)
    public String getCronExpression() {
        return this.cronExpression;
    }
    
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    
    @Column(name="TIME_ZONE_ID", length=80)
    public String getTimeZoneId() {
        return this.timeZoneId;
    }
    
    public void setTimeZoneId(String timeZoneId) {
        this.timeZoneId = timeZoneId;
    }




}


