package com.pavikumbhar.springboot.entity;
// Generated Dec 25, 2016 1:17:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobScheduler generated by hbm2java
 */
@Entity
@Table(name="JOB_SCHEDULER")
public class JobScheduler  implements java.io.Serializable {


     private long jobId;
     private String cronExpression;
     private String createdby;
     private Date createdon;
     private String modifiedby;
     private Date modifiedon;
     private Long pgId;
     private String jobName;
     private String jobDescription;
     private String triggerName;

    public JobScheduler() {
    }

	
    public JobScheduler(long jobId) {
        this.jobId = jobId;
    }
    public JobScheduler(long jobId, String cronExpression, String createdby, Date createdon, String modifiedby, Date modifiedon, Long pgId, String jobName, String jobDescription, String triggerName) {
       this.jobId = jobId;
       this.cronExpression = cronExpression;
       this.createdby = createdby;
       this.createdon = createdon;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
       this.pgId = pgId;
       this.jobName = jobName;
       this.jobDescription = jobDescription;
       this.triggerName = triggerName;
    }
   
     @Id 

    
    @Column(name="JOB_ID", unique=true, nullable=false)
    public long getJobId() {
        return this.jobId;
    }
    
    public void setJobId(long jobId) {
        this.jobId = jobId;
    }

    
    @Column(name="CRON_EXPRESSION", length=50)
    public String getCronExpression() {
        return this.cronExpression;
    }
    
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    
    @Column(name="CREATEDBY", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDON", length=19)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="MODIFIEDBY", length=20)
    public String getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIEDON", length=19)
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    
    @Column(name="PG_ID")
    public Long getPgId() {
        return this.pgId;
    }
    
    public void setPgId(Long pgId) {
        this.pgId = pgId;
    }

    
    @Column(name="JOB_NAME", length=50)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    
    @Column(name="JOB_DESCRIPTION")
    public String getJobDescription() {
        return this.jobDescription;
    }
    
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }

    
    @Column(name="TRIGGER_NAME", length=50)
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }




}


